const data = [
    {Codigo: 'A0001', Descricao: 'Computador Dell'},
    {Codigo: 'A0002', Descricao: 'Computador Positivo'},
    {Codigo: 'A0003', Descricao: 'Computador HP'},
    {Codigo: 'A0004', Descricao: 'Computador LG'},
    {Codigo: 'A0005', Descricao: 'Computador Asus'},
    {Codigo: 'A0006', Descricao: 'Computador Avvel'},
    {Codigo: 'A0007', Descricao: 'Computador da Xuxa'},
    {Codigo: 'A0008', Descricao: 'Notebook Dell'},
    {Codigo: 'A0009', Descricao: 'Notebook Positivo'},
    {Codigo: 'A0010', Descricao: 'Notebook HP'},
    {Codigo: 'A0011', Descricao: 'Notebook MAC'},
    {Codigo: 'A0012', Descricao: 'Notebook Asus'},
    {Codigo: 'A0013', Descricao: 'Notebook Acer'},
    {Codigo: 'A0014', Descricao: 'Notebook Avvel'},
    {Codigo: 'B0001', Descricao: 'Microcomputador Dell'},
    {Codigo: 'B0002', Descricao: 'Microcomputador Positivo'},
    {Codigo: 'B0003', Descricao: 'Microcomputador HP'},
    {Codigo: 'B0004', Descricao: 'Microcomputador LG'},
    {Codigo: 'B0005', Descricao: 'Microcomputador Asus'},
    {Codigo: 'B0006', Descricao: 'Microcomputador Avvel'},
    {Codigo: 'B0007', Descricao: 'Microcomputador da Xuxa'},
    {Codigo: 'B0008', Descricao: 'Ultrabook Dell'},
    {Codigo: 'B0009', Descricao: 'Ultrabook Positivo'},
    {Codigo: 'B0010', Descricao: 'Ultrabook HP'},
    {Codigo: 'B0011', Descricao: 'Ultrabook MAC'},
    {Codigo: 'B0012', Descricao: 'Ultrabook Asus'},
    {Codigo: 'B0013', Descricao: 'Ultrabook Acer'},
    {Codigo: 'B0014', Descricao: 'Ultrabook Avvel'},
    {Codigo: 'C0001', Descricao: 'Memoria Dell'},
    {Codigo: 'C0002', Descricao: 'Memoria Positivo'},
    {Codigo: 'C0003', Descricao: 'Memoria HP'},
    {Codigo: 'C0004', Descricao: 'Memoria LG'},
    {Codigo: 'C0005', Descricao: 'Memoria Asus'},
    {Codigo: 'C0006', Descricao: 'Memoria Avvel'},
    {Codigo: 'C0007', Descricao: 'Memoria da Xuxa'},
    {Codigo: 'C0008', Descricao: 'Mouse sem Fio Dell'},
    {Codigo: 'C0009', Descricao: 'Mouse sem Fio Positivo'},
    {Codigo: 'C0010', Descricao: 'Mouse sem Fio HP'},
    {Codigo: 'C0011', Descricao: 'Mouse sem Fio MAC'},
    {Codigo: 'C0012', Descricao: 'Mouse sem Fio Asus'},
    {Codigo: 'C0013', Descricao: 'Mouse sem Fio Acer'},
    {Codigo: 'C0014', Descricao: 'Mouse sem Fio Avvel'},
    {Codigo: 'D0001', Descricao: 'Mesa Dell'},
    {Codigo: 'D0002', Descricao: 'Mesa Positivo'},
    {Codigo: 'D0003', Descricao: 'Mesa HP'},
    {Codigo: 'D0004', Descricao: 'Mesa LG'},
    {Codigo: 'D0005', Descricao: 'Mesa Asus'},
    {Codigo: 'D0006', Descricao: 'Mesa Avvel'},
    {Codigo: 'D0007', Descricao: 'Mesa da Xuxa'},
    {Codigo: 'D0008', Descricao: 'Mouse com Fio Dell'},
    {Codigo: 'D0009', Descricao: 'Mouse com Fio Positivo'},
    {Codigo: 'D0010', Descricao: 'Mouse com Fio HP'},
    {Codigo: 'D0011', Descricao: 'Mouse com Fio MAC'},
    {Codigo: 'D0012', Descricao: 'Mouse com Fio Asus'},
    {Codigo: 'D0013', Descricao: 'Mouse com Fio Acer'},
    {Codigo: 'D0014', Descricao: 'Mouse com Fio Avvel'},
    {Codigo: 'E0001', Descricao: 'Netbook Dell'},
    {Codigo: 'E0002', Descricao: 'Netbook Positivo'},
    {Codigo: 'E0003', Descricao: 'Netbook HP'},
    {Codigo: 'E0004', Descricao: 'Netbook LG'},
    {Codigo: 'E0005', Descricao: 'Netbook Asus'},
    {Codigo: 'E0006', Descricao: 'Netbook Avvel'},
    {Codigo: 'E0007', Descricao: 'Netbook da Xuxa'},
    {Codigo: 'E0008', Descricao: 'Teclado Dell'},
    {Codigo: 'E0009', Descricao: 'Teclado Positivo'},
    {Codigo: 'E0010', Descricao: 'Teclado HP'},
    {Codigo: 'E0011', Descricao: 'Teclado MAC'},
    {Codigo: 'E0012', Descricao: 'Teclado Asus'},
    {Codigo: 'E0013', Descricao: 'Teclado Acer'},
    {Codigo: 'E0014', Descricao: 'Teclado Avvel'},
];

module.exports = data;